### ISSUE TITLE
missing combo values in uci option

### ISSUE THREAD

**Issue by juliendehos** [zd3nik/SenjoUCIAdapter#2]
Hi.
Thanks for this uci adapter. It does the job very well for the chess engine I'm currently implementing.

It seems the combo values are not sent to the gui. Adding the following lines (UCIAdapter.cpp:529) solved the problem for me:

```
for (std::set<std::string>::const_iterator val = opt->GetComboValues().begin();
    val != opt->GetComboValues().end();
    ++val) {
  out << " var " << *val;
}
```

Regards
Julien

**Comment by zd3nik** [comment]
Hi Julien.

Sorry about that.  I've never used combo box options in any of my engines so I never noticed this.  Thanks for letting me know.  :-)

STC

**Comment by juliendehos** [comment]
You're welcome. Thanks again for senjo.
Julien
